### ISSUE TITLE
Can plugins be run after template document has been created?

### ISSUE THREAD

**Issue by kevinSuttle** [BohemianCoding/SketchTemplates#3]
Hey there, I'm wondering if a plugin can be run after a template document has been created. 
Are there events that are broadcast? 

Example flow: 

File > New From Template > My Scripted Template  
[_opens_]  
[_plugin runs_]

**Comment by bomberstudios** [comment]
Hi Kevin,

that's currently not possible, but it's something that's been in our minds for a while, so it'll be possible, eventually, some day : )
